const state = { metrics: null, alerts: [], history: [], source: null, demo: false, lastErrorCount: 0, reconnectTimer: null };
const $ = (id) => document.getElementById(id);
const fmt = (value) => Number(value || 0).toLocaleString();
const timeAgo = (date) => { const seconds = Math.max(0, Math.floor((Date.now() - new Date(date).getTime()) / 1000)); return seconds < 5 ? 'just now' : seconds < 60 ? `${seconds}s ago` : `${Math.floor(seconds / 60)}m ago`; };

function setConnection(status, label) { $('connectionDot').className = `state-light ${status}`; $('sidebarLight').className = `state-light ${status}`; $('connectionLabel').textContent = label.toUpperCase(); $('sidebarStatus').textContent = label.toUpperCase(); }
function updateMetrics(snapshot) {
  state.metrics = snapshot;
  const services = snapshot.logsByService || {};
  $('totalLogs').textContent = fmt(snapshot.totalLogs); $('totalSmall').textContent = fmt(snapshot.totalLogs);
  $('eventsPerSecond').textContent = Number(snapshot.eventsPerSecond || 0).toFixed(1);
  $('errorRate').textContent = `${Number(snapshot.errorRate || 0).toFixed(1)}%`;
  const errorCount = Number(snapshot.errorLogs || 0);
  $('errorCount').textContent = fmt(errorCount); $('serviceCount').textContent = fmt(Object.keys(services).length);
  if (errorCount > state.lastErrorCount && state.metrics && !state.demo) {
    const delta = errorCount - state.lastErrorCount;
    renderAlert({ serviceName: 'error-stream', message: `${delta} new error ${delta === 1 ? 'event' : 'events'} detected`, timestamp: snapshot.lastEventTimestamp || new Date().toISOString() });
  }
  state.lastErrorCount = errorCount;
  $('infoLogs').textContent = fmt(snapshot.infoLogs); $('warnLogs').textContent = fmt(snapshot.warnLogs); $('errorLogs').textContent = fmt(snapshot.errorLogs);
  const total = Math.max(1, snapshot.totalLogs || 0), info = (snapshot.infoLogs || 0) / total * 100, warn = info + (snapshot.warnLogs || 0) / total * 100;
  $('donut').style.background = `conic-gradient(var(--blue) 0 ${info}%, var(--amber) ${info}% ${warn}%, var(--rose) ${warn}% 100%)`;
  renderServices(services); pushHistory(snapshot); drawChart(); $('chartEmpty').style.display = state.history.length ? 'none' : 'grid';
  $('lastUpdated').textContent = snapshot.lastEventTimestamp ? `Last event ${timeAgo(snapshot.lastEventTimestamp)}` : 'Live stream active';
}
function renderServices(services) { const entries = Object.entries(services).sort((a,b) => b[1] - a[1]); const max = Math.max(1, ...entries.map(([,v]) => v)); $('serviceList').innerHTML = entries.length ? entries.map(([name,count]) => `<div class="service-row"><span class="service-name">${escapeHtml(name)}</span><span class="service-value">${fmt(count)} events</span><div class="bar"><span style="width:${count / max * 100}%"></span></div></div>`).join('') : '<div class="empty-state"><span>◌</span><p>Listening for services</p></div>'; }
function pushHistory(snapshot) { const point = { total: Number(snapshot.totalLogs || 0), errors: Number(snapshot.errorLogs || 0) }; const last = state.history.at(-1); if (!last || last.total !== point.total) state.history.push(point); if (state.history.length > 30) state.history.shift(); }
function drawChart() { const canvas = $('volumeChart'), rect = canvas.getBoundingClientRect(), ratio = window.devicePixelRatio || 1; canvas.width = rect.width * ratio; canvas.height = rect.height * ratio; const ctx = canvas.getContext('2d'); ctx.scale(ratio, ratio); const w = rect.width, h = rect.height, pad = {t:12,r:8,b:25,l:34}; ctx.clearRect(0,0,w,h); ctx.font = '10px DM Mono'; ctx.fillStyle = '#53647c'; for(let i=0;i<4;i++){const y=pad.t+(h-pad.t-pad.b)*i/3;ctx.strokeStyle='#1b2b41';ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();ctx.fillText(i===0?'':`${Math.round(Math.max(...state.history.map(p=>p.total),1)*(3-i)/3)}`,3,y+3)} if(state.history.length<2)return; const max=Math.max(...state.history.map(p=>p.total),1), xStep=(w-pad.l-pad.r)/(state.history.length-1); const path=(key,color,fill=false)=>{ctx.beginPath();state.history.forEach((p,i)=>{const x=pad.l+i*xStep,y=pad.t+(h-pad.t-pad.b)*(1-p[key]/max);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});if(fill){ctx.lineTo(w-pad.r,h-pad.b);ctx.lineTo(pad.l,h-pad.b);ctx.globalAlpha=.12;ctx.fillStyle=color;ctx.fill();ctx.globalAlpha=1}else{ctx.strokeStyle=color;ctx.lineWidth=2;ctx.stroke()}};path('total','#6fa8ff',true);path('total','#6fa8ff');path('errors','#ff718d'); }
function renderAlert(alert) { state.alerts.unshift(alert); state.alerts = state.alerts.slice(0,6); $('navAlertCount').textContent = state.alerts.length; $('activityList').innerHTML = state.alerts.map(item => `<div class="activity-item"><div class="activity-icon">!</div><div class="activity-main"><div class="activity-title">${escapeHtml(item.serviceName || 'System')} · error detected</div><div class="activity-message">${escapeHtml(item.message || 'An error event was received')}</div></div><span class="activity-time">${timeAgo(item.timestamp || Date.now())}</span></div>`).join(''); }
function escapeHtml(text) { return String(text).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function handleEvent(payload) { if (typeof payload === 'string') { try { payload = JSON.parse(payload); } catch { return; } } if (!payload || typeof payload !== 'object') return; const level = String(payload.logLevel || '').toUpperCase(); if ('totalLogs' in payload || 'logsByService' in payload) updateMetrics(payload); else if ('serviceName' in payload && ('message' in payload || level === 'ERROR')) renderAlert(payload); }
function connect() { if (state.source) state.source.close(); if (state.reconnectTimer) clearTimeout(state.reconnectTimer); setConnection('connecting','Connecting'); try { state.source = new EventSource('/api/events'); state.source.onopen = () => { state.demo = false; setConnection('','Live'); }; state.source.onmessage = (event) => handleEvent(event.data); state.source.addEventListener('alert', (event) => handleEvent(event.data)); state.source.onerror = () => { setConnection('offline','Reconnecting'); state.source.close(); state.reconnectTimer = setTimeout(connect, 4000); }; } catch { setConnection('offline','Unavailable'); } }
function startDemo() { if (state.metrics || state.demo) return; state.demo = true; setConnection('connecting','Demo mode'); let tick=0; const services={ 'order-service':42,'payment-service':29,'user-service':18 }; const demoTick=()=>{tick++; const total=89+tick*3; const errors=Math.floor(total*.06); updateMetrics({totalLogs:total,infoLogs:total-errors-7,warnLogs:7,errorLogs:errors,logsByService:services,eventsPerSecond:3.2,errorRate:errors/total*100,lastEventTimestamp:new Date().toISOString()});}; demoTick(); setInterval(()=>{ if(!state.source || state.source.readyState !== 1) demoTick(); },3500); }
$('refreshButton').addEventListener('click', connect); $('clearButton').addEventListener('click', () => { state.alerts=[]; $('navAlertCount').textContent='0'; $('activityList').innerHTML='<div class="empty-state"><span>✓</span><p>No activity yet</p><small>New alerts will appear here in real time.</small></div>'; }); window.addEventListener('resize', drawChart); connect(); setTimeout(startDemo, 1200);
